#!/bin/bash
clear
echo -e "\E[44;1;37m     INSTALACAO BOT SSH VENDAS     \E[0m"
echo -e "\nINSTALANDO AGUARDE...."
apt update -y > /dev/null 2>&1 && apt install unzip at jq curl -y > /dev/null 2>&1
mkdir $HOME/BOT
cd $HOME/BOT && wget github.com/wellzin-blip/scriptssh2/raw/master/instalador/botvendas.zip
unzip botvendas.zip > /dev/null 2>&1 && rm botvendas.zip > /dev/null 2>&1
chmod +x $(ls)
mv botvendas /bin/botvendas
clear && echo -e "INSTALADO COM SUCESSO !\nPARA ATIVAR EXECULTE O COMANDO botvendas"
cd $HOME && rm inst-botvendas > /dev/null 2>&1
